### ISSUE TITLE
Add option for --profile?

### ISSUE THREAD

**Issue by stormeyseas** [quarto-dev/quarto-actions#102]
Love that this action has the to: <format> option, are there also plans to add an equivalent for the --profile options? I'm building a multi-language site using Quarto's profiles feature and I'm hoping to add something like this to my workflow to avoid rendering locally at all costs:
- name: Render default language
- uses: newrenderaction
  - profile: lang1
  - path: docs
- name: Render second language
- uses: newrenderaction
  - profile: lang2
  - path: docs/lang2

**Comment by cscheid** [comment]
We hadn't considered it, but it makes total sense. Would you be willing to contribute a PR?

**Comment by cderv** [comment]
We could definitely add a specific option for this in each action. 

Though today you can do this by setting the `QUARTO_PROFILE` environment variable already
https://quarto.org/docs/projects/profiles.html#activating-profiles

````yaml
      - name: Deploy gh-pages Preview
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          QUARTO_PROFILE: preview
````

We should probably add an example of this at least. 

This will work with any action as it will be picked up by `quarto render` and `quarto publish`
