### ISSUE TITLE
Add an option in setup action to put bundled Pandoc in PATH

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-actions#107]
cc @hadley

With something like this 

```yaml
steps:
    - uses: quarto-dev/quarto-actions/setup@v2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        add-pandoc-to-path: true
```

As we know where Pandoc is in the installed folder, we could add it to `$GITHUB_PATH` to make it available also outside of quarto rendering.
