### ISSUE TITLE
GH Pages error: No previous publishes available to re-publish

### ISSUE THREAD

**Issue by trangdata** [quarto-dev/quarto-actions#22]
Hi, thanks for the neat repo! 💯 🚀 

I have a very basic site created with Quarto (private repo) that I'm trying to set GH Actions for automatic deployment on GH Pages. The repo doesn't yet have a gh-pages branch, and I followed the exact step [here](https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-01-basics.md#github-pages) but am encountering this peculiar error:

```
ERROR: No previous publishes available to re-publish (previous publish required with --no-prompt)
```

Any idea why this is? Thanks a bunch!

<img width="900" alt="ghpages-error" src="https://user-images.githubusercontent.com/1679452/175776458-e2f0ee99-abd5-42a3-9d36-df110188e4d3.png">

**Comment by trangdata** [comment]
My workaround was to change the Deploy step from 

``` yaml
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          to: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
```

to

``` yaml
      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && !github.event.repository.fork
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: build
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          cname: abc.net
```
and this is working for me now.
