### ISSUE TITLE
Add support for subdirectories

### ISSUE THREAD

**Issue by pat-s** [quarto-dev/quarto-actions#23]
E.g. via 

```yml
- name: Publish to RStudio Connect (and render)
  uses: quarto-dev/quarto-actions/publish@v2
    with:
      to: connect
      render_subdir: <subdir>
```
