### ISSUE TITLE
{jsonlite} installation error during publish@v2

### ISSUE THREAD

**Issue by jmgirard** [quarto-dev/quarto-actions#29]
When I try to run `publish@v2`, I get the following error:
> Error in loadNamespace(x) : there is no package called ‘jsonlite’

https://github.com/PittMethods/r4ss/runs/7403069481?check_suite_focus=true

---

My publish.yml was copied directly from: https://quarto.org/docs/publishing/github-pages.html

    on:
      push:
        branches: main
    
    name: Quarto Publish
    
    jobs:
      build-deploy:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
          - name: Check out repository
            uses: actions/checkout@v2
    
          - name: Set up Quarto
            uses: quarto-dev/quarto-actions/setup@v2
    
          - name: Render and Publish
            uses: quarto-dev/quarto-actions/publish@v2
            with:
              target: gh-pages
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Comment by cderv** [comment]
Hi ! 

It seems your document is using R as computation engine, right ? 

In that case there is mainly two scenarios: 

* You are rendering computation locally and have enable freezing in Quarto: https://quarto.org/docs/publishing/github-pages.html#freezing-computations. In that case, no R code should be run during the render. 

* You need to render code chunk during the Quarto rendering phase. In that case you need to configure the execution environment https://quarto.org/docs/publishing/github-pages.html#executing-code. 

It seems you are in the second case: 

* `ubuntu-latest` have a R binary pre installed. 
* `quarto publish` will render the project by default then publish. In your case, rendering requires computation. 
* The error you get is that required packages are not installed. 

See https://quarto.org/docs/publishing/github-pages.html#executing-code part of the documentation and our examples on setting up execution environment: https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-03-dependencies.md
We are recommending to use `r-lib/actions` recipes instead of using the default R installation of the runner. 

Hope it helps understand what is the issue in your workflow.

**Comment by mcanouil** [comment]
If it helps, here a GitHub Action where Quarto relies on R/knitr.
```yaml
on:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            sysfonts
            ggplot2
            ggtext
            showtext
            knitr
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_EMAIL: ${{ github.actor }}@users.noreply.github.com
          target: gh-pages
          path: template.qmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
source: https://github.com/mcanouil/quarto-revealjs-coeos
