### ISSUE TITLE
Adding Quarto Shiny Deploy CI Example

### ISSUE THREAD

**Issue by Lightbridge-KS** [quarto-dev/quarto-actions#34]
Hi, I've an Idea.

I've create GHA workflow that deploy [Shiny app using Quarto](https://quarto.org/docs/interactive/shiny/index.html) using [`{rsconnect}`](https://github.com/rstudio/rsconnect) to shinyapps.io seamlessly, as inspired from this [shiny-deploy](https://github.com/r-lib/actions/blob/v2-branch/examples/shiny-deploy.yaml) action

Here are the example app:

- **Minimal example:** [Faithful App](https://kittipos.shinyapps.io/faithful/) using [shiny-quarto-deploy.yaml](https://github.com/Lightbridge-KS/quarto-shiny-faithful/blob/main/.github/workflows/shiny-quarto-deploy.yaml)
- **More complex:** [TIRADS-Calculator App](https://kittipos.shinyapps.io/tirads-calc/) from this [repo](https://github.com/Lightbridge-KS/tirads-calc)

```yaml

jobs:
  shiny-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book
          tinytex: true
          # uncomment below and fill to pin a version
          # version: 0.9.600

      - name: Set up R Environment
        uses: r-lib/actions/setup-renv@v2 # Installs packages from renv lockfile
        with:
          cache-version: 1

      - name: Install {rsconnect} and {quarto}
        run: |
          renv::install("rsconnect")
          renv::install("quarto")
        shell: Rscript {0}


      - name: Authorize and deploy app
        env: 
          APPNAME: your-app-name
          ACCOUNT: your-account-name
          SERVER: shinyapps.io
        run: |
          rsconnect::setAccountInfo("${{ secrets.RSCONNECT_USER }}", "${{ secrets.RSCONNECT_TOKEN }}", "${{ secrets.RSCONNECT_SECRET }}")
          rsconnect::deployApp(appName = "${{ env.APPNAME }}", account = "${{ env.ACCOUNT }}", server = "${{ env.SERVER }}", quarto = quarto::quarto_path())
        shell: Rscript {0}

```

However, the action must at least install R, `{rsconnect}`, `{quarto}`, and have `shinyapps.io` account.

Do you think is it a good idea to may be include here in the `examples/` section of this repo and write some tutorial ? 
If so, I might able to help you with that.

Thankyou
