### ISSUE TITLE
documentation: render, then publish to GitHub pages (or somewhere else)

### ISSUE THREAD

**Issue by ijlyttle** [quarto-dev/quarto-actions#35]
A lot of times, I will want to render for pull-requests (make sure it still renders) but deploy only on changes to main (having merged a PR).

Would you consider a PR for documentation?

Something like:

```yaml
      - name: Render Quarto
        uses: quarto-dev/quarto-actions/render@v2

      - name: Publish to GitHub Pages
        if: github.event_name != 'pull_request'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          render: false
          target: gh-pages
```

Thanks!
