### ISSUE TITLE
Adapt quarto-actions/setup for use in GitHub Enterprise?

### ISSUE THREAD

**Issue by ijlyttle** [quarto-dev/quarto-actions#40]
I'm starting to experiment with quarto (and r-lib) actions in GitHub Enterprise (GHE). Things are *mostly* working, with a few snags here-and-there.

I have encountered a snag in the setup action:

https://github.com/quarto-dev/quarto-actions/blob/f8db812b12a3c93a53113d4e01910d672e17ab09/setup/action.yml#L42-L43

As I understand, `gh` assumes you are working with GitHub and that you have a valid GitHub token.

I can get around the first problem by adding the host:

```
gh release download --repo github.com/quarto-dev/quarto-cli --pattern ${{ format('*{0}', env.BUNDLE_EXT) }}
```

But the second problem remains: on GHE, `GITHUB_TOKEN` works on GHE - not GitHub proper.

I can work around this problem by specifying a version in my action workflow, e.g.:

```yaml
      - name: Set up Quarto
        uses: <local-fork>/quarto-actions/setup@v2
        with:
          version: 1.0.38
```

Could there be a way to make the "stable release" method robust to use on GitHub Enterprise?

To be clear, this is **not** an urgent issue. The wheels of progress can turn slowly at big companies; we are a long way from rolling anything out internally.

Thanks!

**Comment by ijlyttle** [comment]
I think I see a more-general solution. 

In a local copy of this action, I add the host (as described above):

```
gh release download --repo github.com/quarto-dev/quarto-cli --pattern ${{ format('*{0}', env.BUNDLE_EXT) }}
```

Then, I invoke the workflow:

```yaml
      - name: Set up Quarto
        uses: <local-fork>/quarto-actions/setup@local-test
        env:
          GH_TOKEN: ${{ secrets.GH_GITHUB_COM_TOKEN }}
        with:
         version: pre-release
```

This requires me to place a github.com PAT (no permissions needed) in my actions environment. I read about this workaround in the [documentation for the setup-python action](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#avoiding-rate-limit-issues).

Would you consider a PR? It would include:

  - adding `github.com` as a host qualifier in the action (this would have no effect on "regular" users).
  - adding some documentation on the PAT workaround for Github Enterprise users.

Thanks!
