### ISSUE TITLE
Best practices to install R packages?

### ISSUE THREAD

**Issue by mavam** [quarto-dev/quarto-actions#43]
I'm using quarto-actions in CI, but I'm not sure how to best prepare my R installation.

Here's what I have:

```yaml
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
```

This yields this error:

```
Run quarto-dev/quarto-actions/render@v2
Run if [ "" == "" ]; then
  
Error in loadNamespace(x) : there is no package called ‘jsonlite’
Calls: .main ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted

R installation:
  Version: 4.2.1
  Path: /usr/lib/R
  LibPaths:
    - /usr/local/lib/R/site-library
    - /usr/lib/R/site-library
    - /usr/lib/R/library
  rmarkdown: (None)

The rmarkdown package is not available in this R installation.
Install with install.packages("rmarkdown")

Error: Process completed with exit code 1.
```

How would go after this? Use renv?

**Comment by cderv** [comment]
We have examples and recommandation in the examples section of this  repos. See https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-03-dependencies.md

You'll find also some example in our doc in the Publishing section: https://quarto.org/docs/publishing/ci.html#github-actions

Example with `quarto publish` section and executing code: https://quarto.org/docs/publishing/quarto-pub#executing-code

Hopefully, you'll find everything you need. If not, please do tell us so that we improve.

**Comment by mavam** [comment]
Thanks for the pointers! I looked through them but couldn't find recommendations on how to manage package dependencies. Specifically, I'm looking to install a subset of `tidyverse`. How would I go after it?

I tried this:
```yaml
      - name: Install tidyverse
        run: install.packages("tidyverse")
        shell: Rscript {0}
```

But I'm not getting very far:

```
ERROR: configuration failed for package ‘curl’
* removing ‘/home/runner/work/vast/vast/renv/staging/1/curl’
Traceback (most recent calls last):
12: install.packages("tidyverse")
11: install(pkgs)
10: renv_install_impl(records)
 9: renv_install_staged(records)
 8: renv_install_default(records)
 7: handler(package, renv_install_package(record))
 6: renv_install_package(record)
 5: withCallingHandlers(renv_install_package_impl(record), error = function(e) {
        vwritef("\tFAILED")
        writef(e$output)
    })
 4: renv_install_package_impl(record)
 3: r_cmd_install(package, path)
 2: r_exec_error(package, output, "install", status)
 1: stop(error)
Execution halted
Error: Process completed with exit code 1.
```

It was also an 8min installation process, which feels a bit too long.

I followed closely the docs, but it looks like I'm missing something very fundamental. I tried then this:

```
- uses: r-lib/actions/setup-r-dependencies@v2
  with:
    cache-version: 2
    extra-packages: |
      any::tidyverse
```

But it turns out I need a `DESCRIPTION` file in my top-level repo:

```
   x Cannot install packages:
  * deps::.: No root directory found in /home/runner/work/vast/vast or its parent directories. Root criterion: contains a file "DESCRIPTION" with contents matching "^Package: " 
  Execution halted
  Error: Process completed with exit code 1.
```

So now I'm a bit lost. My quarto project is in subdirectory `web/` relative to the top-level directory. I'm not sure in which direction to go forward to make it work.
