### ISSUE TITLE
Render action randomly fails when exporting to PDF: ERROR: Couldn't find open server

### ISSUE THREAD

**Issue by rogerbramon** [quarto-dev/quarto-actions#45]
Occasionally, `quarto-actions/render@v2` fails to run, causing `ERROR: Couldn't find open server`.  I've only experienced this problem when rendering to PDF, HTML output seems fine.

<img width="478" alt="image" src="https://user-images.githubusercontent.com/330441/189908374-b4e4872a-fd4f-43a8-b331-24fbebd8cf40.png">

Has anyone experienced it?

Tested on:
Ubuntu 20.04 and 22.04
Quarto: latest version (1.1.189) and fixing one (1.0.37)

Workflow example:

```yaml
name: Generate PDF
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  generate-pdf:
    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        tinytex: true

    - name: Quarto check
      run: |
        quarto check --log-level info

    - name: Render Quarto Project
      uses: quarto-dev/quarto-actions/render@v2
      with:
        to: pdf
        path: input/P123-qmd-file.qmd

```

This is the output of all Quarto actions of the workflow when fails:

![quarto-render-output](https://user-images.githubusercontent.com/330441/189911507-712416ab-52c9-48a5-9d1f-f157f3c80423.jpg)

**Comment by cscheid** [comment]
This is the first time I see this error. Thank you for the report!

**Comment by rogerbramon** [comment]
> @rogerbramon can you share more on the `.qmd` content where this error happens ? Do you have a link of the project ?

Content is basically pure Markdown and a mermaid diagram using ` ```{mermaid} ` format.
Unfortunately, it's a private repo, but I could try to create a test one and try to reproduce it there.

**Comment by rogerbramon** [comment]
Here you have the test repo, and I was able to reproduce the problem at the 3rd attempt (same code, just re-run jobs).

Successful attempt: https://github.com/rogerbramon/test-quarto/actions/runs/3045981181/attempts/2
Failure attempt: https://github.com/rogerbramon/test-quarto/actions/runs/3045981181

**Comment by cderv** [comment]
> I was able to reproduce the problem at the 3rd attempt (same code, just re-run jobs).

It seems not good that this is working on some run, and not on other... Like internal issue in the runners with connecting to chrome headless. 🤔

**Comment by rogerbramon** [comment]
Could it be that sometimes the Google Chrome takes a bit longer to spin up? If I get it right, you have a timeout of only 3 seconds on  `waitForServer`. 

https://github.com/quarto-dev/quarto-cli/blob/ed57d10eba33c34b5e1df2c22ed372a7e28da5d0/src/core/cri/cri.ts#L80-L90

I tried adding a previous step that calls the Chrome headless, and the problem is not occurring then. That's why timeout is my guess... Any thoughts? 

```yaml
    - name: Check chrome
      run: |
        echo $(which google-chrome)
        $(which google-chrome) --headless --single-process https://www.chromestatus.com
```
