### ISSUE TITLE
Line 22: syntax error near unexpected token `fi'

### ISSUE THREAD

**Issue by tomicapretto** [quarto-dev/quarto-actions#59]
Hello! 

I'm using setup@v2 and push@v2 actions in my repository https://github.com/estadisticaunr/estadistica-bayesiana. It used to work well, but recently I got a couple of failures with the following message

<details>

```shell
if [ Linux != "Windows" ]; then
    # On Windows scoop will be used so no need to download the release
    if [ -z "" ]; then
      # download the latest stable release
      gh release download --repo quarto-dev/quarto-cli --pattern *linux-amd64.deb
      version=$(curl https://quarto.org/docs/download/_download.json | jq -r '.version')
      echo "version=${version}" >> $GITHUB_OUTPUT
    elif [ "" == "LATEST" -o "" == "pre-release" ]; then
      # get latest pre release version 
      version=$(curl https://quarto.org/docs/download/_prerelease.json | jq -r '.version')
      wget https://github.com/quarto-dev/quarto-cli/releases/download/v$version/quarto-$version-linux-amd64.deb
      echo "version=${version}" >> $GITHUB_OUTPUT
    else
      # download a specific release
      wget https://github.com/quarto-dev/quarto-cli/releases/download/v/quarto--linux-amd64.deb
      echo "version=" >> $GITHUB_OUTPUT
    fi
    echo "installer=$(ls quarto*linux-amd64.deb)" >> $GITHUB_OUTPUT
  else
    # FIXME: how to get version information from scoop in windows runners?
    # send the cderv bat-signal!
  fi
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    R_LIBS_USER: /home/runner/work/_temp/Library
    TZ: UTC
    _R_CHECK_SYSTEM_CLOCK_: FALSE
    NOT_CRAN: true
    R_LIB_FOR_PAK: /opt/R/4.2.2/lib/R/site-library
    BUNDLE_EXT: linux-amd64.deb
    GITHUB_TOKEN: ***
/home/runner/work/_temp/a93c4f63-ea4e-4723-b14e-90932[37](https://github.com/estadisticaunr/estadistica-bayesiana/actions/runs/3830766211/jobs/6519056612#step:5:39)bc6c5.sh: line 22: syntax error near unexpected token `fi'
Error: Process completed with exit code 2.
```
</details>

This is the YAML file

<details>

```yaml

on:
  push:
    branches: main

name: Renderizar y publicar página web

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          packages: |
            any::here
            any::rmarkdown
            any::knitr
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2    
        
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

</details>

Is this a problem with the action? I'm not sure, since I don't see it has changed. But anyway, I think this is a good place to consult.

Thanks al lot!
