### ISSUE TITLE
Action to install specific version of Quarto

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [quarto-dev/quarto-actions#6]
A feature request: It would be great to have a sample action here for installing a specific version of Quarto, in addition to the existing action that installs the latest.

**Comment by cderv** [comment]
Yes I think I can add that. 

The specific version would be the in release https://github.com/quarto-dev/quarto-cli/releases 

Would that be ok ?

**Comment by mine-cetinkaya-rundel** [comment]
Yeah, that would be fine, thank you!

**Comment by cderv** [comment]
This should now be possible 

```yaml
    steps:
      - uses: quarto-dev/quarto-actions/install-quarto@main
        with:
          version: 0.3.71
```

Not yet in a tagged version so you need to point to `main`
