### ISSUE TITLE
Can this action be used to publish a single .qmd document?

### ISSUE THREAD

**Issue by Aariq** [quarto-dev/quarto-actions#61]
It appears that this action only works with projects that are type: website or type: book.  Is there a way to use this action to just publish a single document?  Do I need to have something like the following in _quarto.yml?

``` yaml
project:
  title: "proj-title"
  execute-dir: project
  render:
    - docs/my_document.Qmd
  type: website
```

This allows me to use the action, I think, but messes up my targets pipeline because `tarchetypes::tar_quarto()` expects the rendered .html to be in the same directory as the .Qmd file.  Changing the `output-dir` to "docs" just causes the .qmd file to be deleted on rendering.
