### ISSUE TITLE
TinyTex version error

### ISSUE THREAD

**Issue by arnold-c** [quarto-dev/quarto-actions#71]
I'm trying to use the Quarto GitHub Action to render and publish a book in both the PDF and HTML format, but unfortunately it is producing the following error when trying to render the PDF output.

```
ERROR: Your TexLive version is not updated enough to connect to the remote repository and download packages. Please update your installation of TexLive or TinyTex.

Underlying message: Local TeX Live (2022) is older than remote repository (2023).
```

I have tried a number of different things to update the CTAN repository manually, using a different pdf-engine, etc, but unfortunately none of them seem to work.

Any thoughts would be appreciated.

```
on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
        env:
          GH_TOKEN: ${{ secrets.QUARTO_PUBLISH_TOKEN }}
          
      - name: Publish HTML book
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: true

```
